In [1]:
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  1 09:15:34 2020

@author: DHRUV
"""


"""
HW3 (c) (ii)

"""

"""
We have 88 instances/datasets. Each instance has 6 features. For each instance, we'll summarize the data
for each feature of an instance. So for instance 1, say, we have 6 features from feature_1, feature_2,....
......, to feature_6. feature_1 has it's own min, max, mean, median, standard deviation, first quartile and third 
quartile. Each feature, thus, in each instance, has 7 feature summary. 7*6 = 42 columns thus exist in our
data summary. The total rows are the total instances, that is, 88. 

So the data summary has dimension 88 x 42 size.

Also as we have to summarize for each instance, we assume that no training, test splitting is needed here, as,
in the question the first few instances for each action were characterized as test and the remaining as train.
Here as all instances are to be summarized, this is the summary of the entire data, including test and train 
instances, in general, for every single action.

All the datasets have been, for python and pandas use, appropriately modified and named in Excel itself

"""

import pandas as pd
import numpy as np

b1_1 = pd.read_csv('bending1\\test\\dataset1.csv')
print(b1_1)
b1_2 = pd.read_csv('bending1\\test\\dataset2.csv')
print(b1_2)
b1_3 = pd.read_csv('bending1\\training\\dataset3.csv')
print(b1_3)
b1_4 = pd.read_csv('bending1\\training\\dataset4.csv')
print(b1_4)
b1_5 = pd.read_csv('bending1\\training\\dataset5.csv')
print(b1_5)
b1_6 = pd.read_csv('bending1\\training\\dataset6.csv')
print(b1_6)
b1_7 = pd.read_csv('bending1\\training\\dataset7.csv')
print(b1_7)



b2_1 = pd.read_csv('bending2\\test\\dataset1.csv')
print(b2_1)
b2_2 = pd.read_csv('bending2\\test\\dataset2.csv')
print(b2_2)
b2_3 = pd.read_csv('bending2\\training\\dataset3.csv')
print(b2_3)
b2_4 = pd.read_csv('bending2\\training\\dataset4.csv')
print(b2_4)
b2_5 = pd.read_csv('bending2\\training\\dataset5.csv')
print(b2_5)
b2_6 = pd.read_csv('bending2\\training\\dataset6.csv')
print(b2_6)


cy_1 = pd.read_csv('cycling\\test\\dataset1.csv')
print(cy_1)
cy_2 = pd.read_csv('cycling\\test\\dataset2.csv')
print(cy_2)
cy_3 = pd.read_csv('cycling\\test\\dataset3.csv')
print(cy_3)
cy_4 = pd.read_csv('cycling\\training\\dataset4.csv')
print(cy_4)
cy_5 = pd.read_csv('cycling\\training\\dataset5.csv')
print(cy_5)
cy_6 = pd.read_csv('cycling\\training\\dataset6.csv')
print(cy_6)
cy_7 = pd.read_csv('cycling\\training\\dataset7.csv')
print(cy_7)
cy_8 = pd.read_csv('cycling\\training\\dataset8.csv')
print(cy_8)
cy_9 = pd.read_csv('cycling\\training\\dataset9.csv')
print(cy_9)
cy_10 = pd.read_csv('cycling\\training\\dataset10.csv')
print(cy_10)
cy_11 = pd.read_csv('cycling\\training\\dataset11.csv')
print(cy_11)
cy_12 = pd.read_csv('cycling\\training\\dataset12.csv')
print(cy_12)
cy_13 = pd.read_csv('cycling\\training\\dataset13.csv')
print(cy_13)
cy_14 = pd.read_csv('cycling\\training\\dataset14.csv')
print(cy_14)
cy_15 = pd.read_csv('cycling\\training\\dataset15.csv')
print(cy_15)




ly_1 = pd.read_csv('lying\\test\\dataset1.csv')
print(ly_1)
ly_2 = pd.read_csv('lying\\test\\dataset2.csv')
print(ly_2)
ly_3 = pd.read_csv('lying\\test\\dataset3.csv')
print(ly_3)
ly_4 = pd.read_csv('lying\\training\\dataset4.csv')
print(ly_4)
ly_5 = pd.read_csv('lying\\training\\dataset5.csv')
print(ly_5)
ly_6 = pd.read_csv('lying\\training\\dataset6.csv')
print(ly_6)
ly_7 = pd.read_csv('lying\\training\\dataset7.csv')
print(ly_7)
ly_8 = pd.read_csv('lying\\training\\dataset8.csv')
print(ly_8)
ly_9 = pd.read_csv('lying\\training\\dataset9.csv')
print(ly_9)
ly_10 = pd.read_csv('lying\\training\\dataset10.csv')
print(ly_10)
ly_11 = pd.read_csv('lying\\training\\dataset11.csv')
print(ly_11)
ly_12 = pd.read_csv('lying\\training\\dataset12.csv')
print(ly_12)
ly_13 = pd.read_csv('lying\\training\\dataset13.csv')
print(ly_13)
ly_14 = pd.read_csv('lying\\training\\dataset14.csv')
print(ly_14)
ly_15 = pd.read_csv('lying\\training\\dataset15.csv')
print(ly_15)






sit_1 = pd.read_csv('sitting\\test\\dataset1.csv')
print(sit_1)
sit_2 = pd.read_csv('sitting\\test\\dataset2.csv')
print(sit_2)
sit_3 = pd.read_csv('sitting\\test\\dataset3.csv')
print(sit_3)
sit_4 = pd.read_csv('sitting\\training\\dataset4.csv')
print(sit_4)
sit_5 = pd.read_csv('sitting\\training\\dataset5.csv')
print(sit_5)
sit_6 = pd.read_csv('sitting\\training\\dataset6.csv')
print(sit_6)
sit_7 = pd.read_csv('sitting\\training\\dataset7.csv')
print(sit_7)
sit_8 = pd.read_csv('sitting\\training\\dataset8.csv')
print(sit_8)
sit_9 = pd.read_csv('sitting\\training\\dataset9.csv')
print(sit_9)
sit_10 = pd.read_csv('sitting\\training\\dataset10.csv')
print(sit_10)
sit_11 = pd.read_csv('sitting\\training\\dataset11.csv')
print(sit_11)
sit_12 = pd.read_csv('sitting\\training\\dataset12.csv')
print(sit_12)
sit_13 = pd.read_csv('sitting\\training\\dataset13.csv')
print(sit_13)
sit_14 = pd.read_csv('sitting\\training\\dataset14.csv')
print(sit_14)
sit_15 = pd.read_csv('sitting\\training\\dataset15.csv')
print(sit_15)




stand_1 = pd.read_csv('standing\\test\\dataset1.csv')
print(stand_1)
stand_2 = pd.read_csv('standing\\test\\dataset2.csv')
print(stand_2)
stand_3 = pd.read_csv('standing\\test\\dataset3.csv')
print(stand_3)
stand_4 = pd.read_csv('standing\\training\\dataset4.csv')
print(stand_4)
stand_5 = pd.read_csv('standing\\training\\dataset5.csv')
print(stand_5)
stand_6 = pd.read_csv('standing\\training\\dataset6.csv')
print(stand_6)
stand_7 = pd.read_csv('standing\\training\\dataset7.csv')
print(stand_7)
stand_8 = pd.read_csv('standing\\training\\dataset8.csv')
print(stand_8)
stand_9 = pd.read_csv('standing\\training\\dataset9.csv')
print(stand_9)
stand_10 = pd.read_csv('standing\\training\\dataset10.csv')
print(stand_10)
stand_11 = pd.read_csv('standing\\training\\dataset11.csv')
print(stand_11)
stand_12 = pd.read_csv('standing\\training\\dataset12.csv')
print(stand_12)
stand_13 = pd.read_csv('standing\\training\\dataset13.csv')
print(stand_13)
stand_14 = pd.read_csv('standing\\training\\dataset14.csv')
print(stand_14)
stand_15 = pd.read_csv('standing\\training\\dataset15.csv')
print(stand_15)






wa_1 = pd.read_csv('walking\\test\\dataset1.csv')
print(wa_1)
wa_2 = pd.read_csv('walking\\test\\dataset2.csv')
print(wa_2)
wa_3 = pd.read_csv('walking\\test\\dataset3.csv')
print(wa_3)
wa_4 = pd.read_csv('walking\\training\\dataset4.csv')
print(wa_4)
wa_5 = pd.read_csv('walking\\training\\dataset5.csv')
print(wa_5)
wa_6 = pd.read_csv('walking\\training\\dataset6.csv')
print(wa_6)
wa_7 = pd.read_csv('walking\\training\\dataset7.csv')
print(wa_7)
wa_8 = pd.read_csv('walking\\training\\dataset8.csv')
print(wa_8)
wa_9 = pd.read_csv('walking\\training\\dataset9.csv')
print(wa_9)
wa_10 = pd.read_csv('walking\\training\\dataset10.csv')
print(wa_10)
wa_11 = pd.read_csv('walking\\training\\dataset11.csv')
print(wa_11)
wa_12 = pd.read_csv('walking\\training\\dataset12.csv')
print(wa_12)
wa_13 = pd.read_csv('walking\\training\\dataset13.csv')
print(wa_13)
wa_14 = pd.read_csv('walking\\training\\dataset14.csv')
print(wa_14)
wa_15 = pd.read_csv('walking\\training\\dataset15.csv')
print(wa_15)



headers = ['avg_rss12_mean', 'avg_rss12_std', 'avg_rss12_min', 'avg_rss12_q1','avg_rss12_median', 'avg_rss12_q3','avg_rss12_max','var_rss12_mean', 'var_rss12_std', 'var_rss12_min', 'var_rss12_q1','var_rss12_median', 'var_rss12_q3','var_rss12_max','avg_rss13_mean', 'avg_rss13_std', 'avg_rss13_min', 'avg_rss13_q1','avg_rss13_median', 'avg_rss13_q3','avg_rss13_max','var_rss13_mean', 'var_rss13_std', 'var_rss13_min', 'var_rss13_q1','var_rss13_median', 'var_rss13_q3','var_rss13_max','avg_rss23_mean', 'avg_rss23_std', 'avg_rss23_min', 'avg_rss23_q1','avg_rss23_median', 'avg_rss23_q3','avg_rss23_max','var_rss23_mean', 'var_rss23_std', 'var_rss23_min', 'var_rss23_q1','var_rss23_median', 'var_rss23_q3','var_rss23_max']
names_of_instances = ['b1_1','b1_2','b1_3','b1_4','b1_5','b1_6','b1_7','b2_1','b2_2','b2_3','b2_4','b2_5','b2_6','cy_1','cy_2','cy_3','cy_4','cy_5','cy_6','cy_7','cy_8','cy_9','cy_10','cy_11','cy_12','cy_13','cy_14','cy_15','ly_1','ly_2','ly_3','ly_4','ly_5','ly_6','ly_7','ly_8','ly_9','ly_10','ly_11','ly_12','ly_13','ly_14','ly_15','sit_1','sit_2','sit_3','sit_4','sit_5','sit_6','sit_7','sit_8','sit_9','sit_10','sit_11','sit_12','sit_13','sit_14','sit_15','stand_1','stand_2','stand_3','stand_4','stand_5','stand_6','stand_7','stand_8','stand_9','stand_10','stand_11','stand_12','stand_13','stand_14','stand_15','wa_1','wa_2','wa_3','wa_4','wa_5','wa_6','wa_7','wa_8','wa_9','wa_10','wa_11','wa_12','wa_13','wa_14','wa_15']
final_df = pd.DataFrame(columns = headers, index = names_of_instances)
print(final_df)


d_b1_1 = b1_1.drop(columns = ['time_b1_1']).describe()
d_b1_1 = d_b1_1.iloc[1:8,:]
d_b1_1_flat = d_b1_1.to_numpy().flatten('F')
final_df.iloc[0,:] = d_b1_1_flat



d_b1_2 = b1_2.drop(columns = ['time_b1_2']).describe()
d_b1_2 = d_b1_2.iloc[1:8,:]
d_b1_2_flat = d_b1_2.to_numpy().flatten('F')
final_df.iloc[1,:] = d_b1_2_flat



d_b1_3 = b1_3.drop(columns = ['time_b1_3']).describe()
d_b1_3 = d_b1_3.iloc[1:8,:]
d_b1_3_flat = d_b1_3.to_numpy().flatten('F')
final_df.iloc[2,:] = d_b1_3_flat



d_b1_4 = b1_4.drop(columns = ['time_b1_4']).describe()
d_b1_4 = d_b1_4.iloc[1:8,:]
d_b1_4_flat = d_b1_4.to_numpy().flatten('F')
final_df.iloc[3,:] = d_b1_4_flat


d_b1_5 = b1_5.drop(columns = ['time_b1_5']).describe()
d_b1_5 = d_b1_5.iloc[1:8,:]
d_b1_5_flat = d_b1_5.to_numpy().flatten('F')
final_df.iloc[4,:] = d_b1_5_flat


d_b1_6 = b1_6.drop(columns = ['time_b1_6']).describe()
d_b1_6 = d_b1_6.iloc[1:8,:]
d_b1_6_flat = d_b1_6.to_numpy().flatten('F')
final_df.iloc[5,:] = d_b1_6_flat


d_b1_7 = b1_7.drop(columns = ['time_b1_7']).describe()
d_b1_7 = d_b1_7.iloc[1:8,:]
d_b1_7_flat = d_b1_7.to_numpy().flatten('F')
final_df.iloc[6,:] = d_b1_7_flat









d_b2_1 = b2_1.drop(columns = ['time_b2_1']).describe()
d_b2_1 = d_b2_1.iloc[1:8,:]
d_b2_1_flat = d_b2_1.to_numpy().flatten('F')
final_df.iloc[7,:] = d_b2_1_flat


d_b2_2 = b2_2.drop(columns = ['time_b2_2']).describe()
d_b2_2 = d_b2_2.iloc[1:8,:]
d_b2_2_flat = d_b2_2.to_numpy().flatten('F')
final_df.iloc[8,:] = d_b2_2_flat


d_b2_3 = b2_3.drop(columns = ['time_b2_3']).describe()
d_b2_3 = d_b2_3.iloc[1:8,:]
d_b2_3_flat = d_b2_3.to_numpy().flatten('F')
final_df.iloc[9,:] = d_b2_3_flat


d_b2_4 = b2_4.drop(columns = ['time_b2_4']).describe()
d_b2_4 = d_b2_4.iloc[1:8,:]
d_b2_4_flat = d_b2_4.to_numpy().flatten('F')
final_df.iloc[10,:] = d_b2_4_flat

d_b2_5 = b2_5.drop(columns = ['time_b2_5']).describe()
d_b2_5 = d_b2_5.iloc[1:8,:]
d_b2_5_flat = d_b2_5.to_numpy().flatten('F')
final_df.iloc[11,:] = d_b2_5_flat


d_b2_6 = b2_6.drop(columns = ['time_b2_6']).describe()
d_b2_6 = d_b2_6.iloc[1:8,:]
d_b2_6_flat = d_b2_6.to_numpy().flatten('F')
final_df.iloc[12,:] = d_b2_6_flat












d_cy_1 = cy_1.drop(columns = ['time_cy_1']).describe()
d_cy_1 = d_cy_1.iloc[1:8,:]
d_cy_1_flat = d_cy_1.to_numpy().flatten('F')
final_df.iloc[13,:] = d_cy_1_flat


d_cy_2 = cy_2.drop(columns = ['time_cy_2']).describe()
d_cy_2 = d_cy_2.iloc[1:8,:]
d_cy_2_flat = d_cy_2.to_numpy().flatten('F')
final_df.iloc[14,:] = d_cy_2_flat


d_cy_3 = cy_3.drop(columns = ['time_cy_3']).describe()
d_cy_3 = d_cy_3.iloc[1:8,:]
d_cy_3_flat = d_cy_3.to_numpy().flatten('F')
final_df.iloc[15,:] = d_cy_3_flat


d_cy_4 = cy_4.drop(columns = ['time_cy_4']).describe()
d_cy_4 = d_cy_4.iloc[1:8,:]
d_cy_4_flat = d_cy_4.to_numpy().flatten('F')
final_df.iloc[16,:] = d_cy_4_flat


d_cy_5 = cy_5.drop(columns = ['time_cy_5']).describe()
d_cy_5 = d_cy_5.iloc[1:8,:]
d_cy_5_flat = d_cy_5.to_numpy().flatten('F')
final_df.iloc[17,:] = d_cy_5_flat


d_cy_6 = cy_6.drop(columns = ['time_cy_6']).describe()
d_cy_6 = d_cy_6.iloc[1:8,:]
d_cy_6_flat = d_cy_6.to_numpy().flatten('F')
final_df.iloc[18,:] = d_cy_6_flat


d_cy_7 = cy_7.drop(columns = ['time_cy_7']).describe()
d_cy_7 = d_cy_7.iloc[1:8,:]
d_cy_7_flat = d_cy_7.to_numpy().flatten('F')
final_df.iloc[19,:] = d_cy_7_flat


d_cy_8 = cy_8.drop(columns = ['time_cy_8']).describe()
d_cy_8 = d_cy_8.iloc[1:8,:]
d_cy_8_flat = d_cy_8.to_numpy().flatten('F')
final_df.iloc[20,:] = d_cy_8_flat


d_cy_9 = cy_9.drop(columns = ['time_cy_9']).describe()
d_cy_9 = d_cy_9.iloc[1:8,:]
d_cy_9_flat = d_cy_9.to_numpy().flatten('F')
final_df.iloc[21,:] = d_cy_9_flat


d_cy_10 = cy_10.drop(columns = ['time_cy_10']).describe()
d_cy_10 = d_cy_10.iloc[1:8,:]
d_cy_10_flat = d_cy_10.to_numpy().flatten('F')
final_df.iloc[22,:] = d_cy_10_flat


d_cy_11 = cy_11.drop(columns = ['time_cy_11']).describe()
d_cy_11 = d_cy_11.iloc[1:8,:]
d_cy_11_flat = d_cy_11.to_numpy().flatten('F')
final_df.iloc[23,:] = d_cy_11_flat


d_cy_12 = cy_12.drop(columns = ['time_cy_12']).describe()
d_cy_12 = d_cy_12.iloc[1:8,:]
d_cy_12_flat = d_cy_12.to_numpy().flatten('F')
final_df.iloc[24,:] = d_cy_12_flat


d_cy_13 = cy_13.drop(columns = ['time_cy_13']).describe()
d_cy_13 = d_cy_13.iloc[1:8,:]
d_cy_13_flat = d_cy_13.to_numpy().flatten('F')
final_df.iloc[25,:] = d_cy_13_flat


d_cy_14 = cy_14.drop(columns = ['time_cy_14']).describe()
d_cy_14 = d_cy_14.iloc[1:8,:]
d_cy_14_flat = d_cy_14.to_numpy().flatten('F')
final_df.iloc[26,:] = d_cy_14_flat



d_cy_15 = cy_15.drop(columns = ['time_cy_15']).describe()
d_cy_15 = d_cy_15.iloc[1:8,:]
d_cy_15_flat = d_cy_15.to_numpy().flatten('F')
final_df.iloc[27,:] = d_cy_15_flat


















d_ly_1 = ly_1.drop(columns = ['time_ly_1']).describe()
d_ly_1 = d_ly_1.iloc[1:8,:]
d_ly_1_flat = d_ly_1.to_numpy().flatten('F')
final_df.iloc[28,:] = d_ly_1_flat


d_ly_2 = ly_2.drop(columns = ['time_ly_2']).describe()
d_ly_2 = d_ly_2.iloc[1:8,:]
d_ly_2_flat = d_ly_2.to_numpy().flatten('F')
final_df.iloc[29,:] = d_ly_2_flat


d_ly_3 = ly_3.drop(columns = ['time_ly_3']).describe()
d_ly_3 = d_ly_3.iloc[1:8,:]
d_ly_3_flat = d_ly_3.to_numpy().flatten('F')
final_df.iloc[30,:] = d_ly_3_flat


d_ly_4 = ly_4.drop(columns = ['time_ly_4']).describe()
d_ly_4 = d_ly_4.iloc[1:8,:]
d_ly_4_flat = d_ly_4.to_numpy().flatten('F')
final_df.iloc[31,:] = d_ly_4_flat


d_ly_5 = ly_5.drop(columns = ['time_ly_5']).describe()
d_ly_5 = d_ly_5.iloc[1:8,:]
d_ly_5_flat = d_ly_5.to_numpy().flatten('F')
final_df.iloc[32,:] = d_ly_5_flat


d_ly_6 = ly_6.drop(columns = ['time_ly_6']).describe()
d_ly_6 = d_ly_6.iloc[1:8,:]
d_ly_6_flat = d_ly_6.to_numpy().flatten('F')
final_df.iloc[33,:] = d_ly_6_flat


d_ly_7 = ly_7.drop(columns = ['time_ly_7']).describe()
d_ly_7 = d_ly_7.iloc[1:8,:]
d_ly_7_flat = d_ly_7.to_numpy().flatten('F')
final_df.iloc[34,:] = d_ly_7_flat


d_ly_8 = ly_8.drop(columns = ['time_ly_8']).describe()
d_ly_8 = d_ly_8.iloc[1:8,:]
d_ly_8_flat = d_ly_8.to_numpy().flatten('F')
final_df.iloc[35,:] = d_ly_8_flat


d_ly_9 = ly_9.drop(columns = ['time_ly_9']).describe()
d_ly_9 = d_ly_9.iloc[1:8,:]
d_ly_9_flat = d_ly_9.to_numpy().flatten('F')
final_df.iloc[36,:] = d_ly_9_flat


d_ly_10 = ly_10.drop(columns = ['time_ly_10']).describe()
d_ly_10 = d_ly_10.iloc[1:8,:]
d_ly_10_flat = d_ly_10.to_numpy().flatten('F')
final_df.iloc[37,:] = d_ly_10_flat


d_ly_11 = ly_11.drop(columns = ['time_ly_11']).describe()
d_ly_11 = d_ly_11.iloc[1:8,:]
d_ly_11_flat = d_ly_11.to_numpy().flatten('F')
final_df.iloc[38,:] = d_ly_11_flat


d_ly_12 = ly_12.drop(columns = ['time_ly_12']).describe()
d_ly_12 = d_ly_12.iloc[1:8,:]
d_ly_12_flat = d_ly_12.to_numpy().flatten('F')
final_df.iloc[39,:] = d_ly_12_flat


d_ly_13 = ly_13.drop(columns = ['time_ly_13']).describe()
d_ly_13 = d_ly_13.iloc[1:8,:]
d_ly_13_flat = d_ly_13.to_numpy().flatten('F')
final_df.iloc[40,:] = d_ly_13_flat


d_ly_14 = ly_14.drop(columns = ['time_ly_14']).describe()
d_ly_14 = d_ly_14.iloc[1:8,:]
d_ly_14_flat = d_ly_14.to_numpy().flatten('F')
final_df.iloc[41,:] = d_ly_14_flat



d_ly_15 = ly_15.drop(columns = ['time_ly_15']).describe()
d_ly_15 = d_ly_15.iloc[1:8,:]
d_ly_15_flat = d_ly_15.to_numpy().flatten('F')
final_df.iloc[42,:] = d_ly_15_flat




















d_sit_1 = sit_1.drop(columns = ['time_sit_1']).describe()
d_sit_1 = d_sit_1.iloc[1:8,:]
d_sit_1_flat = d_sit_1.to_numpy().flatten('F')
final_df.iloc[43,:] = d_sit_1_flat


d_sit_2 = sit_2.drop(columns = ['time_sit_2']).describe()
d_sit_2 = d_sit_2.iloc[1:8,:]
d_sit_2_flat = d_sit_2.to_numpy().flatten('F')
final_df.iloc[44,:] = d_sit_2_flat


d_sit_3 = sit_3.drop(columns = ['time_sit_3']).describe()
d_sit_3 = d_sit_3.iloc[1:8,:]
d_sit_3_flat = d_sit_3.to_numpy().flatten('F')
final_df.iloc[45,:] = d_sit_3_flat


d_sit_4 = sit_4.drop(columns = ['time_sit_4']).describe()
d_sit_4 = d_sit_4.iloc[1:8,:]
d_sit_4_flat = d_sit_4.to_numpy().flatten('F')
final_df.iloc[46,:] = d_sit_4_flat


d_sit_5 = sit_5.drop(columns = ['time_sit_5']).describe()
d_sit_5 = d_sit_5.iloc[1:8,:]
d_sit_5_flat = d_sit_5.to_numpy().flatten('F')
final_df.iloc[47,:] = d_sit_5_flat


d_sit_6 = sit_6.drop(columns = ['time_sit_6']).describe()
d_sit_6 = d_sit_6.iloc[1:8,:]
d_sit_6_flat = d_sit_6.to_numpy().flatten('F')
final_df.iloc[48,:] = d_sit_6_flat


d_sit_7 = sit_7.drop(columns = ['time_sit_7']).describe()
d_sit_7 = d_sit_7.iloc[1:8,:]
d_sit_7_flat = d_sit_7.to_numpy().flatten('F')
final_df.iloc[49,:] = d_sit_7_flat


d_sit_8 = sit_8.drop(columns = ['time_sit_8']).describe()
d_sit_8 = d_sit_8.iloc[1:8,:]
d_sit_8_flat = d_sit_8.to_numpy().flatten('F')
final_df.iloc[50,:] = d_sit_8_flat


d_sit_9 = sit_9.drop(columns = ['time_sit_9']).describe()
d_sit_9 = d_sit_9.iloc[1:8,:]
d_sit_9_flat = d_sit_9.to_numpy().flatten('F')
final_df.iloc[51,:] = d_sit_9_flat


d_sit_10 = sit_10.drop(columns = ['time_sit_10']).describe()
d_sit_10 = d_sit_10.iloc[1:8,:]
d_sit_10_flat = d_sit_10.to_numpy().flatten('F')
final_df.iloc[52,:] = d_sit_10_flat


d_sit_11 = sit_11.drop(columns = ['time_sit_11']).describe()
d_sit_11 = d_sit_11.iloc[1:8,:]
d_sit_11_flat = d_sit_11.to_numpy().flatten('F')
final_df.iloc[53,:] = d_sit_11_flat


d_sit_12 = sit_12.drop(columns = ['time_sit_12']).describe()
d_sit_12 = d_sit_12.iloc[1:8,:]
d_sit_12_flat = d_sit_12.to_numpy().flatten('F')
final_df.iloc[54,:] = d_sit_12_flat


d_sit_13 = sit_13.drop(columns = ['time_sit_13']).describe()
d_sit_13 = d_sit_13.iloc[1:8,:]
d_sit_13_flat = d_sit_13.to_numpy().flatten('F')
final_df.iloc[55,:] = d_sit_13_flat


d_sit_14 = sit_14.drop(columns = ['time_sit_14']).describe()
d_sit_14 = d_sit_14.iloc[1:8,:]
d_sit_14_flat = d_sit_14.to_numpy().flatten('F')
final_df.iloc[56,:] = d_sit_14_flat



d_sit_15 = sit_15.drop(columns = ['time_sit_15']).describe()
d_sit_15 = d_sit_15.iloc[1:8,:]
d_sit_15_flat = d_sit_15.to_numpy().flatten('F')
final_df.iloc[57,:] = d_sit_15_flat












d_stand_1 = stand_1.drop(columns = ['time_stand_1']).describe()
d_stand_1 = d_stand_1.iloc[1:8,:]
d_stand_1_flat = d_stand_1.to_numpy().flatten('F')
final_df.iloc[58,:] = d_stand_1_flat


d_stand_2 = stand_2.drop(columns = ['time_stand_2']).describe()
d_stand_2 = d_stand_2.iloc[1:8,:]
d_stand_2_flat = d_stand_2.to_numpy().flatten('F')
final_df.iloc[59,:] = d_stand_2_flat


d_stand_3 = stand_3.drop(columns = ['time_stand_3']).describe()
d_stand_3 = d_stand_3.iloc[1:8,:]
d_stand_3_flat = d_stand_3.to_numpy().flatten('F')
final_df.iloc[60,:] = d_stand_3_flat


d_stand_4 = stand_4.drop(columns = ['time_stand_4']).describe()
d_stand_4 = d_stand_4.iloc[1:8,:]
d_stand_4_flat = d_stand_4.to_numpy().flatten('F')
final_df.iloc[61,:] = d_stand_4_flat


d_stand_5 = stand_5.drop(columns = ['time_stand_5']).describe()
d_stand_5 = d_stand_5.iloc[1:8,:]
d_stand_5_flat = d_stand_5.to_numpy().flatten('F')
final_df.iloc[62,:] = d_stand_5_flat


d_stand_6 = stand_6.drop(columns = ['time_stand_6']).describe()
d_stand_6 = d_stand_6.iloc[1:8,:]
d_stand_6_flat = d_stand_6.to_numpy().flatten('F')
final_df.iloc[63,:] = d_stand_6_flat


d_stand_7 = stand_7.drop(columns = ['time_stand_7']).describe()
d_stand_7 = d_stand_7.iloc[1:8,:]
d_stand_7_flat = d_stand_7.to_numpy().flatten('F')
final_df.iloc[64,:] = d_stand_7_flat


d_stand_8 = stand_8.drop(columns = ['time_stand_8']).describe()
d_stand_8 = d_stand_8.iloc[1:8,:]
d_stand_8_flat = d_stand_8.to_numpy().flatten('F')
final_df.iloc[65,:] = d_stand_8_flat


d_stand_9 = stand_9.drop(columns = ['time_stand_9']).describe()
d_stand_9 = d_stand_9.iloc[1:8,:]
d_stand_9_flat = d_stand_9.to_numpy().flatten('F')
final_df.iloc[66,:] = d_stand_9_flat


d_stand_10 = stand_10.drop(columns = ['time_stand_10']).describe()
d_stand_10 = d_stand_10.iloc[1:8,:]
d_stand_10_flat = d_stand_10.to_numpy().flatten('F')
final_df.iloc[67,:] = d_stand_10_flat


d_stand_11 = stand_11.drop(columns = ['time_stand_11']).describe()
d_stand_11 = d_stand_11.iloc[1:8,:]
d_stand_11_flat = d_stand_11.to_numpy().flatten('F')
final_df.iloc[68,:] = d_stand_11_flat


d_stand_12 = stand_12.drop(columns = ['time_stand_12']).describe()
d_stand_12 = d_stand_12.iloc[1:8,:]
d_stand_12_flat = d_stand_12.to_numpy().flatten('F')
final_df.iloc[69,:] = d_stand_12_flat


d_stand_13 = stand_13.drop(columns = ['time_stand_13']).describe()
d_stand_13 = d_stand_13.iloc[1:8,:]
d_stand_13_flat = d_stand_13.to_numpy().flatten('F')
final_df.iloc[70,:] = d_stand_13_flat


d_stand_14 = stand_14.drop(columns = ['time_stand_14']).describe()
d_stand_14 = d_stand_14.iloc[1:8,:]
d_stand_14_flat = d_stand_14.to_numpy().flatten('F')
final_df.iloc[71,:] = d_stand_14_flat



d_stand_15 = stand_15.drop(columns = ['time_stand_15']).describe()
d_stand_15 = d_stand_15.iloc[1:8,:]
d_stand_15_flat = d_stand_15.to_numpy().flatten('F')
final_df.iloc[72,:] = d_stand_15_flat

















d_wa_1 = wa_1.drop(columns = ['time_wa_1']).describe()
d_wa_1 = d_wa_1.iloc[1:8,:]
d_wa_1_flat = d_wa_1.to_numpy().flatten('F')
final_df.iloc[73,:] = d_wa_1_flat


d_wa_2 = wa_2.drop(columns = ['time_wa_2']).describe()
d_wa_2 = d_wa_2.iloc[1:8,:]
d_wa_2_flat = d_wa_2.to_numpy().flatten('F')
final_df.iloc[74,:] = d_wa_2_flat


d_wa_3 = wa_3.drop(columns = ['time_wa_3']).describe()
d_wa_3 = d_wa_3.iloc[1:8,:]
d_wa_3_flat = d_wa_3.to_numpy().flatten('F')
final_df.iloc[75,:] = d_wa_3_flat


d_wa_4 = wa_4.drop(columns = ['time_wa_4']).describe()
d_wa_4 = d_wa_4.iloc[1:8,:]
d_wa_4_flat = d_wa_4.to_numpy().flatten('F')
final_df.iloc[76,:] = d_wa_4_flat


d_wa_5 = wa_5.drop(columns = ['time_wa_5']).describe()
d_wa_5 = d_wa_5.iloc[1:8,:]
d_wa_5_flat = d_wa_5.to_numpy().flatten('F')
final_df.iloc[77,:] = d_wa_5_flat


d_wa_6 = wa_6.drop(columns = ['time_wa_6']).describe()
d_wa_6 = d_wa_6.iloc[1:8,:]
d_wa_6_flat = d_wa_6.to_numpy().flatten('F')
final_df.iloc[78,:] = d_wa_6_flat


d_wa_7 = wa_7.drop(columns = ['time_wa_7']).describe()
d_wa_7 = d_wa_7.iloc[1:8,:]
d_wa_7_flat = d_wa_7.to_numpy().flatten('F')
final_df.iloc[79,:] = d_wa_7_flat


d_wa_8 = wa_8.drop(columns = ['time_wa_8']).describe()
d_wa_8 = d_wa_8.iloc[1:8,:]
d_wa_8_flat = d_wa_8.to_numpy().flatten('F')
final_df.iloc[80,:] = d_wa_8_flat


d_wa_9 = wa_9.drop(columns = ['time_wa_9']).describe()
d_wa_9 = d_wa_9.iloc[1:8,:]
d_wa_9_flat = d_wa_9.to_numpy().flatten('F')
final_df.iloc[81,:] = d_wa_9_flat


d_wa_10 = wa_10.drop(columns = ['time_wa_10']).describe()
d_wa_10 = d_wa_10.iloc[1:8,:]
d_wa_10_flat = d_wa_10.to_numpy().flatten('F')
final_df.iloc[82,:] = d_wa_10_flat


d_wa_11 = wa_11.drop(columns = ['time_wa_11']).describe()
d_wa_11 = d_wa_11.iloc[1:8,:]
d_wa_11_flat = d_wa_11.to_numpy().flatten('F')
final_df.iloc[83,:] = d_wa_11_flat


d_wa_12 = wa_12.drop(columns = ['time_wa_12']).describe()
d_wa_12 = d_wa_12.iloc[1:8,:]
d_wa_12_flat = d_wa_12.to_numpy().flatten('F')
final_df.iloc[84,:] = d_wa_12_flat


d_wa_13 = wa_13.drop(columns = ['time_wa_13']).describe()
d_wa_13 = d_wa_13.iloc[1:8,:]
d_wa_13_flat = d_wa_13.to_numpy().flatten('F')
final_df.iloc[85,:] = d_wa_13_flat


d_wa_14 = wa_14.drop(columns = ['time_wa_14']).describe()
d_wa_14 = d_wa_14.iloc[1:8,:]
d_wa_14_flat = d_wa_14.to_numpy().flatten('F')
final_df.iloc[86,:] = d_wa_14_flat



d_wa_15 = wa_15.drop(columns = ['time_wa_15']).describe()
d_wa_15 = d_wa_15.iloc[1:8,:]
d_wa_15_flat = d_wa_15.to_numpy().flatten('F')
final_df.iloc[87,:] = d_wa_15_flat





print(final_df)

final_df.to_csv('Extracted_Whole_Feature.csv')



"""

Extracted_Wholed_Features is a .csv file containing the required data, a summary
of each instance


"""

     time_b1_1  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      39.25       0.43      22.75       0.43      33.75
1          250      39.25       0.43      23.00       0.00      33.00
2          500      39.25       0.43      23.25       0.43      33.00
3          750      39.50       0.50      23.00       0.71      33.00
4         1000      39.50       0.50      24.00       0.00      33.00
..         ...        ...        ...        ...        ...        ...
475     118750      43.33       0.47      25.00       0.00      30.00
476     119000      43.50       0.50      25.50       0.50      30.00
477     119250      43.50       0.50      24.75       0.43      30.00
478     119500      43.50       0.50      24.33       0.47      30.00
479     119750      43.50       0.50      24.25       0.43      30.00

     var_rss23
0          1.3
1          0.0
2          0.0
3          0.0
4          0.0
..         ...
475        0.0
476        0.0
477        0.0
478        0.0
479        0.0

[480 rows x 7 columns]
     time_b1_2  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      43.67       0.47      24.75       0.43      30.00
1          250      43.33       0.47      25.33       0.47      30.00
2          500      42.75       0.83      25.25       0.83      30.50
3          750      41.75       0.43      20.50       3.35      30.75
4         1000      42.50       0.50      20.75       4.55      31.75
..         ...        ...        ...        ...        ...        ...
475     118750      43.00       0.71       9.50       2.18      30.25
476     119000      43.25       0.83      12.25       0.43      32.50
477     119250      43.50       0.50      13.00       2.35      32.50
478     119500      43.75       0.43      15.75       1.92      31.50
479     119750      43.25       0.83      20.75       0.43      31.00

     var_rss23
0         0.00
1         0.00
2         0.50
3         0.83
4         0.43
..         ...
475       0.43
476       0.50
477       0.87
478       0.50
479       0.71

[480 rows x 7 columns]
     time_b1_3  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      42.00       0.71      21.25       0.43      30.00
1          250      41.50       0.50      20.25       1.48      31.25
2          500      41.50       0.50      14.25       1.92      33.00
3          750      40.75       0.83      15.75       0.43      33.00
4         1000      40.00       0.71      20.00       2.74      32.75
..         ...        ...        ...        ...        ...        ...
475     118750      42.50       0.50      20.00       0.82      36.00
476     119000      42.67       0.47      21.00       0.00      36.33
477     119250      44.33       0.94      21.00       0.00      36.33
478     119500      45.25       0.43      26.75       1.79      36.00
479     119750      47.25       0.83      29.75       0.43      35.25

     var_rss23
0         0.00
1         1.09
2         0.00
3         0.00
4         0.43
..         ...
475       0.00
476       0.47
477       0.47
478       0.00
479       1.30

[480 rows x 7 columns]
     time_b1_4  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      47.33       0.47      28.00       0.82      34.25
1          250      47.50       0.50      29.00       1.22      36.00
2          500      47.50       0.50      30.00       0.00      36.75
3          750      47.00       0.71      28.00       1.22      37.00
4         1000      45.00       0.71      24.25       1.79      36.00
..         ...        ...        ...        ...        ...        ...
475     118750      39.00       0.00      11.50       4.72      23.75
476     119000      41.50       0.50      22.25       1.92      26.25
477     119250      42.00       0.00      23.50       0.87      29.75
478     119500      42.50       0.50      21.00       0.00      30.00
479     119750      43.25       0.43      23.75       0.43      28.25

     var_rss23
0         1.30
1         0.00
2         0.83
3         1.22
4         0.00
..         ...
475       0.43
476       1.30
477       0.43
478       0.00
479       0.43

[480 rows x 7 columns]
     time_b1_5  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      44.33       0.47      23.75       0.43      30.00
1          250      44.50       0.50      24.00       0.00      30.25
2          500      44.00       0.71      24.00       0.00      30.50
3          750      43.00       0.71      21.75       1.30      31.50
4         1000      42.75       0.43      25.00       2.24      35.25
..         ...        ...        ...        ...        ...        ...
475     118750      42.50       0.87      21.50       0.50      30.50
476     119000      42.50       0.50      21.00       0.00      30.00
477     119250      42.25       0.43      20.75       0.43      30.00
478     119500      40.50       1.12      23.50       0.87      29.50
479     119750      41.50       0.87      24.00       0.00      30.00

     var_rss23
0         0.00
1         0.43
2         0.50
3         1.12
4         1.30
..         ...
475       0.50
476       0.00
477       0.00
478       0.50
479       0.00

[480 rows x 7 columns]
     time_b1_6  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      41.25       1.30      24.00       0.00      32.33
1          250      41.00       1.00      22.50       1.12      33.50
2          500      44.25       0.83      21.75       0.83      31.50
3          750      45.00       0.00      20.00       1.22      30.00
4         1000      45.25       0.43      15.25       2.86      30.50
..         ...        ...        ...        ...        ...        ...
475     118750      43.50       0.50      14.50       1.12      22.50
476     119000      44.00       0.00      18.00       0.71      22.25
477     119250      44.25       0.83      16.50       2.29      23.25
478     119500      42.50       0.87      13.50       1.50      16.25
479     119750      41.50       0.50      15.25       1.79      13.00

     var_rss23
0         0.94
1         0.87
2         1.50
3         0.00
4         0.50
..         ...
475       0.87
476       1.09
477       1.30
478       3.11
479       1.22

[480 rows x 7 columns]
     time_b1_7  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      42.00       0.00      18.50       0.50      12.00
1          250      42.00       0.00      18.00       0.00      11.33
2          500      42.75       0.43      16.75       1.79      18.25
3          750      42.50       0.50      16.75       0.83      19.00
4         1000      43.00       0.82      16.25       0.83      18.00
..         ...        ...        ...        ...        ...        ...
475     118750      44.25       0.83      16.25       1.30      24.00
476     119000      44.00       0.71      11.00       1.00      24.00
477     119250      44.25       0.43      10.25       1.30      22.75
478     119500      43.75       0.43       7.33       2.87      21.50
479     119750      44.50       0.50       3.00       1.22      21.50

     var_rss23
0         0.00
1         0.94
2         0.43
3         1.22
4         0.00
..         ...
475       0.00
476       0.00
477       0.83
478       0.50
479       0.50

[480 rows x 7 columns]
     time_b2_1  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      23.75       0.43      24.00       0.00      24.67
1          250      22.67       0.94      24.00       0.00      24.67
2          500      21.33       0.47      24.00       0.00      24.75
3          750      21.00       0.00      24.00       0.00      25.25
4         1000      23.00       0.71      23.75       0.43      24.75
..         ...        ...        ...        ...        ...        ...
475     118750      27.50       0.50      22.75       1.30      21.00
476     119000      27.00       0.00      21.00       0.00      20.75
477     119250      27.00       0.00      21.00       0.00      20.50
478     119500      27.25       0.43      23.50       0.87      20.75
479     119750      27.00       0.00      24.00       0.00      19.25

     var_rss23
0         0.47
1         0.94
2         0.83
3         1.09
4         0.83
..         ...
475       0.00
476       1.09
477       0.50
478       0.43
479       0.83

[480 rows x 7 columns]
     time_b2_2  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      27.00       0.00      24.00       0.00      19.00
1          250      27.00       0.00      24.00       0.00      19.75
2          500      27.00       0.00      23.50       0.50      20.00
3          750      27.00       0.00      24.00       0.00      14.75
4         1000      27.00       0.00      23.75       0.43      14.50
..         ...        ...        ...        ...        ...        ...
475     118750      23.00       0.71      11.25       2.49      26.75
476     119000      22.25       0.43      15.50       0.87      29.50
477     119250      23.75       0.43      17.67       0.47      25.67
478     119500      24.25       0.43      13.33       1.25      30.00
479     119750      25.33       0.47      14.75       1.09      25.33

     var_rss23
0         1.00
1         0.83
2         1.22
3         1.48
4         1.50
..         ...
475       1.92
476       1.50
477       3.09
478       2.45
479       3.68

[480 rows x 7 columns]
     time_b2_3  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      24.50       0.50      15.50       0.87      26.00
1          250      25.00       0.00      13.50       3.64      33.50
2          500      26.00       0.71      14.25       3.90      18.50
3          750      24.33       0.47      15.67       2.62      25.50
4         1000      23.50       0.87      16.25       1.30      23.00
..         ...        ...        ...        ...        ...        ...
475     118750      33.00       0.00       1.25       0.43      19.00
476     119000      33.00       0.00       3.75       0.83      19.00
477     119250      33.00       0.00       5.25       1.30      18.50
478     119500      32.75       0.43       2.50       0.50      19.25
479     119750      32.67       0.47       2.00       1.00      19.00

     var_rss23
0         2.74
1         2.60
2        13.61
3         3.64
4         1.22
..         ...
475       1.00
476       1.00
477       0.50
478       0.83
479       1.00

[480 rows x 7 columns]
     time_b2_4  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0       32.5        0.5          0          0         19
1            1       32.5        0.5          0          0         19
2            2       32.5        0.5          0          0         19
3            3       32.5        0.5          0          0         19
4            4       32.5        0.5          0          0         19
..         ...        ...        ...        ...        ...        ...
475        475       32.5        0.5          0          0         19
476        476       32.5        0.5          0          0         19
477        477       32.5        0.5          0          0         19
478        478       32.5        0.5          0          0         19
479        479       32.5        0.5          0          0         19

     var_rss23
0            1
1            1
2            1
3            1
4            1
..         ...
475          1
476          1
477          1
478          1
479          1

[480 rows x 7 columns]
     time_b2_5  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      28.00       0.00       0.00       0.00      17.25
1          250      29.00       0.00       0.00       0.00      17.33
2          500      28.67       0.47       0.00       0.00      17.00
3          750      29.00       0.00       3.00       2.00      17.67
4         1000      29.00       0.00       3.33       0.47      18.00
..         ...        ...        ...        ...        ...        ...
475     118750      36.00       0.00      18.00       0.00      27.75
476     119000      36.25       0.43      14.50       2.87      27.00
477     119250      36.00       0.00       8.67       2.49      27.00
478     119500      36.80       0.98      13.00       0.63      27.75
479     119750      35.00       1.41       7.00       2.00      27.50

     var_rss23
0         0.83
1         0.94
2         0.82
3         0.47
4         1.00
..         ...
475       0.43
476       0.71
477       0.00
478       0.43
479       0.50

[480 rows x 7 columns]
     time_b2_6  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      34.50       1.50       8.00       1.58      28.00
1          250      36.00       0.00      11.25       3.49      28.50
2          500      36.00       0.00      20.00       1.22      27.00
3          750      38.25       0.43      21.25       0.43      26.00
4         1000      37.50       1.12      22.00       0.82      23.67
..         ...        ...        ...        ...        ...        ...
475     118750      27.00       0.00      14.00       0.00       6.50
476     119000      27.00       0.00      15.00       0.00       4.00
477     119250      27.00       0.00      14.25       0.83       4.00
478     119500      27.00       0.00      13.33       1.25       1.50
479     119750      26.50       0.50      15.00       0.00       3.00

     var_rss23
0         0.71
1         0.50
2         0.71
3         0.71
4         2.49
..         ...
475       0.50
476       1.00
477       2.00
478       0.50
479       0.00

[480 rows x 7 columns]
     time_cy_1  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      32.00       4.85      17.50       3.35      22.50
1          250      40.50       1.12      14.00       2.24      21.75
2          500      40.50       2.60      11.33       4.50      18.25
3          750      34.50       1.50      20.67       2.87      19.00
4         1000      34.50       1.50      21.25       3.27      18.25
..         ...        ...        ...        ...        ...        ...
475     118750      38.00       2.55      18.25       2.17      20.00
476     119000      36.00       0.00      19.00       1.41      13.67
477     119250      37.00       1.73      17.75       0.43      22.50
478     119500      37.00       3.74      19.00       4.18      22.00
479     119750      38.75       1.92      16.75       3.49      21.00

     var_rss23
0         3.20
1         1.30
2         5.31
3         2.83
4         4.38
..         ...
475       4.74
476       1.25
477       0.87
478       1.41
479       3.67

[480 rows x 7 columns]
     time_cy_2  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      41.75       1.79       8.75       6.87      23.25
1          250      39.50       3.57      15.00       0.00      19.25
2          500      35.00       1.41      19.33       1.25      19.50
3          750      36.00       0.00      18.50       0.50      21.25
4         1000      33.33       2.87      20.25       1.79      23.75
..         ...        ...        ...        ...        ...        ...
475     118750      42.33       0.47       6.67       3.77      20.33
476     119000      43.00       1.41      11.67       2.49      14.00
477     119250      36.75       1.09      16.75       3.03      21.50
478     119500      36.33       0.47      20.33       2.05      20.50
479     119750      35.25       1.30      16.50       1.12      22.75

     var_rss23
0         0.83
1         3.27
2         3.20
3         4.76
4         0.43
..         ...
475       0.47
476       5.10
477       2.60
478       2.18
479       2.17

[480 rows x 7 columns]
     time_cy_3  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      35.50       3.84      19.75       2.77      20.25
1          250      33.50      12.99      16.50       4.72      22.50
2          500      42.00       0.00       9.00       3.67      20.25
3          750      41.50       1.50      12.33       0.47      18.00
4         1000      35.25       2.49      19.50       3.35      24.25
..         ...        ...        ...        ...        ...        ...
475     118750      36.50       1.50      15.67       9.74      20.50
476     119000      36.00       0.00      23.25       1.30      17.00
477     119250      32.33       5.56      15.33       3.77      14.50
478     119500      32.00       5.87      12.25       2.17      14.50
479     119750      38.00       2.12      16.50       3.20      11.25

     var_rss23
0         3.27
1         1.50
2         1.30
3         2.45
4         0.43
..         ...
475       2.87
476       1.63
477       4.82
478       2.87
479       5.80

[480 rows x 7 columns]
     time_cy_4  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      40.50       2.60      17.25       3.90      15.50
1          250      35.50       1.50      19.75       1.30      18.50
2          500      35.25       1.30      13.67       6.13      18.50
3          750      35.25       3.90      14.75       3.27      21.25
4         1000      32.25       2.49      10.67       6.60      15.50
..         ...        ...        ...        ...        ...        ...
475     118750      36.00       3.67      19.75       2.05      21.50
476     119000      31.75       1.09      20.67       1.89      14.00
477     119250      37.67       5.44      18.50       1.50      13.00
478     119500      34.67       5.44      17.00       1.00      15.25
479     119750      40.50       1.12      17.75       2.38      17.50

     var_rss23
0         3.28
1         3.77
2         0.50
3         1.79
4         4.39
..         ...
475       2.18
476       3.74
477       4.55
478       4.44
479       1.50

[480 rows x 7 columns]
     time_cy_5  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      39.33       2.36      15.00       4.24      13.50
1          250      33.00       2.45      20.25       1.92      18.67
2          500      31.50       5.59      19.00       4.97      19.50
3          750      34.50       4.72      14.00       5.89      16.00
4         1000      39.00       1.58      14.67       3.68      19.50
..         ...        ...        ...        ...        ...        ...
475     118750      36.00       4.24      15.50       8.20      17.00
476     119000      34.00       2.12      22.50       4.50      16.00
477     119250      33.25       6.57      20.00       3.74      22.67
478     119500      39.50       1.50      17.75       1.79      16.25
479     119750      41.75       0.43      12.67       2.36      17.33

     var_rss23
0         3.20
1         0.47
2         0.50
3         4.58
4         1.50
..         ...
475       3.67
476       1.87
477       0.94
478       1.79
479       2.05

[480 rows x 7 columns]
     time_cy_6  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      37.00       1.00      20.00       6.16      21.25
1          250      34.33       2.36      20.25      10.57      11.67
2          500      31.00       3.56      18.67       2.49      18.50
3          750      36.75       2.86      13.75       2.86      19.50
4         1000      42.00       0.71      13.25       2.05      19.00
..         ...        ...        ...        ...        ...        ...
475     118750      41.25       1.92      11.67       6.94      16.67
476     119000      43.25       0.83      10.67       4.50      18.50
477     119250      35.25       4.44      12.60       1.36      11.80
478     119500      35.25       1.30      16.00       0.82      16.33
479     119750      35.50       4.61      16.25       2.05      15.67

     var_rss23
0         2.17
1         1.25
2         2.60
3         1.50
4         1.87
..         ...
475       2.62
476       1.80
477       7.68
478       3.09
479       1.70

[480 rows x 7 columns]
     time_cy_7  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \

     time_ly_4  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      48.00       0.00       9.00       0.00       9.25
1          250      48.00       0.00       9.00       0.00       9.50
2          500      48.00       0.00      10.00       0.71      10.00
3          750      48.00       0.00       9.50       0.50       9.50
4         1000      48.00       0.00      10.00       0.00      10.00
..         ...        ...        ...        ...        ...        ...
475     118750      39.33       0.47      12.00       0.00       0.00
476     119000      40.25       0.43      12.00       0.00       1.00
477     119250      39.75       0.83      12.00       0.00       0.00
478     119500      40.25       0.83      12.00       0.00       0.00
479     119750      39.75       0.83      12.25       0.43       1.00

     var_rss23
0         0.43
1         0.50
2         0.71
3         0.50
4         1.00
..         ...
475       0.00
476       0.00
477       0.00
478       0.00
479       0.00

[480 rows x 7 columns]
     time_ly_5  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      39.50       0.50      12.00       0.00       0.00
1          250      39.75       0.83      13.00       0.00       0.00
2          500      40.00       1.00      12.67       0.47       0.00
3          750      40.00       0.71      12.50       0.50       1.00
4         1000      40.00       0.82      12.50       0.87       1.50
..         ...        ...        ...        ...        ...        ...
475     118750      39.50       0.50       8.25       0.83      13.25
476     119000      39.67       0.47       6.00       0.00      13.50
477     119250      39.50       0.50       7.60       0.49      13.50
478     119500      39.50       0.50       8.33       0.47      14.33
479     119750      39.50       0.50       8.50       0.50      14.50

     var_rss23
0         0.00
1         0.00
2         0.00
3         0.00
4         0.50
..         ...
475       0.83
476       0.50
477       1.12
478       0.47
479       0.50

[480 rows x 7 columns]
     time_ly_6  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      39.67       0.47       8.75       0.43      14.67
1          250      39.67       0.47       8.75       0.43      14.67
2          500      39.33       0.47       8.00       0.82      14.25
3          750      39.67       0.47       7.50       0.50      13.67
4         1000      39.33       0.47       9.00       0.00      13.50
..         ...        ...        ...        ...        ...        ...
475     118750      39.50       0.50       6.75       2.49      12.75
476     119000      39.25       0.43       9.75       0.43      12.50
477     119250      39.50       0.50       9.75       0.43      12.75
478     119500      39.67       0.47       9.50       0.50      13.33
479     119750      39.50       0.50       9.00       0.00      12.67

     var_rss23
0         0.47
1         0.47
2         0.43
3         1.25
4         0.50
..         ...
475       0.83
476       0.50
477       0.83
478       0.94
479       0.47

[480 rows x 7 columns]
     time_ly_7  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      39.50       0.50       4.33       1.25      12.00
1          250      39.50       0.50       7.00       0.00      12.33
2          500      39.50       0.50       6.33       2.49      11.75
3          750      39.67       0.47       8.75       1.30      12.67
4         1000      39.50       0.50       5.00       0.71      11.75
..         ...        ...        ...        ...        ...        ...
475     118750      39.50       0.50       3.00       0.00      18.00
476     119000      39.67       0.47       3.00       0.00      17.67
477     119250      39.00       0.00       2.00       0.00      18.00
478     119500      39.00       0.00       2.00       0.00      18.00
479     119750      39.00       0.00       2.00       0.00      18.00

     var_rss23
0         0.00
1         0.47
2         0.43
3         0.47
4         0.43
..         ...
475       0.00
476       0.47
477       0.00
478       0.00
479       0.00

[480 rows x 7 columns]
     time_ly_8  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      39.58       0.49       1.92       0.73      17.67
1          250      39.25       0.43       2.00       0.71      17.75
2          500      39.25       0.43       1.67       0.94      17.67
3          750      39.50       0.50       2.67       0.47      17.75
4         1000      39.50       0.50       1.00       0.00      17.75
..         ...        ...        ...        ...        ...        ...
475     118750      39.25       0.43       6.00       2.74      16.25
476     119000      39.00       0.00       4.00       2.55      13.75
477     119250      39.50       0.50       7.50       0.50      13.00
478     119500      39.50       0.50       6.75       0.83      15.00
479     119750      39.50       0.50       6.50       0.50      16.50

     var_rss23
0         0.47
1         0.43
2         0.47
3         0.43
4         0.43
..         ...
475       2.05
476       1.30
477       1.22
478       1.41
479       1.12

[480 rows x 7 columns]
     time_ly_9  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      39.67       0.47       6.00       0.82      16.00
1          250      39.50       0.50       4.50       1.12      17.75
2          500      39.67       0.47       4.50       1.12      18.33
3          750      39.50       0.50       4.50       2.06      17.50
4         1000      39.33       0.47       5.33       0.47      17.00
..         ...        ...        ...        ...        ...        ...
475     118750      41.50       0.50      10.67       0.47      14.00
476     119000      41.50       0.50      10.80       0.40      14.40
477     119250      41.75       0.43      10.00       0.00      13.67
478     119500      42.00       0.00       9.40       0.49      14.00
479     119750      41.75       0.43       9.00       0.00      14.33

     var_rss23
0         1.00
1         0.43
2         0.47
3         0.50
4         0.71
..         ...
475       0.82
476       0.80
477       0.94
478       1.10
479       0.47

[480 rows x 7 columns]
     time_ly_10  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0      29.00       0.00       9.00       0.71       8.50
1           250      29.00       0.00       8.00       0.71       8.50
2           500      29.00       0.00       8.00       0.71       8.00
3           750      28.50       0.50       8.25       0.43       8.75
4          1000      29.00       0.00       8.75       1.09       9.00
..          ...        ...        ...        ...        ...        ...
475      118750      29.25       0.43       4.00       0.00      10.50
476      119000      29.25       0.43       4.00       0.00      10.25
477      119250      29.50       0.50       2.33       0.94       9.67
478      119500      29.00       0.00       2.67       0.47      10.00
479      119750      29.00       0.00       2.75       0.43      11.00

     var_rss23
0         0.50
1         0.50
2         1.00
3         0.43
4         0.00
..         ...
475       0.50
476       0.83
477       0.94
478       0.82
479       0.82

[480 rows x 7 columns]
     time_ly_11  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0       48.0        0.0       6.25       0.43       2.00
1           250       48.0        0.0       6.00       0.00       1.67
2           500       48.0        0.0       6.00       0.00       2.00
3           750       48.0        0.0       5.25       0.43       2.67
4          1000       48.0        0.0       5.50       0.50       2.00
..          ...        ...        ...        ...        ...        ...
475      118750       48.0        0.0       7.75       0.43      11.25
476      119000       48.0        0.0       8.33       0.47       9.67
477      119250       48.0        0.0       8.75       0.43       9.50
478      119500       48.0        0.0       9.00       0.00       9.75
479      119750       48.0        0.0       9.00       0.00       9.33

     var_rss23
0         0.71
1         0.94
2         1.00
3         0.94
4         0.82
..         ...
475       0.83
476       0.47
477       0.50
478       0.83
479       0.47

[480 rows x 7 columns]
     time_ly_12  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0      39.50       0.50      12.00       0.00       0.00
1           250      39.75       0.83      13.00       0.00       0.00
2           500      40.00       1.00      12.67       0.47       0.00
3           750      40.00       0.71      12.50       0.50       1.00
4          1000      40.00       0.82      12.50       0.87       1.50
..          ...        ...        ...        ...        ...        ...
475      118750      39.50       0.50       8.25       0.83      13.25
476      119000      39.67       0.47       6.00       0.00      13.50
477      119250      39.50       0.50       7.60       0.49      13.50
478      119500      39.50       0.50       8.33       0.47      14.33
479      119750      39.50       0.50       8.50       0.50      14.50

     var_rss23
0         0.00
1         0.00
2         0.00
3         0.00
4         0.50
..         ...
475       0.83
476       0.50
477       1.12
478       0.47
479       0.50

[480 rows x 7 columns]
     time_ly_13  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0      39.50       0.50       4.33       1.25      12.00
1           250      39.50       0.50       7.00       0.00      12.33
2           500      39.50       0.50       6.33       2.49      11.75
3           750      39.67       0.47       8.75       1.30      12.67
4          1000      39.50       0.50       5.00       0.71      11.75
..          ...        ...        ...        ...        ...        ...
475      118750      39.50       0.50       3.00       0.00      18.00
476      119000      39.67       0.47       3.00       0.00      17.67
477      119250      39.00       0.00       2.00       0.00      18.00
478      119500      39.00       0.00       2.00       0.00      18.00
479      119750      39.00       0.00       2.00       0.00      18.00

     var_rss23
0         0.00
1         0.47
2         0.43
3         0.47
4         0.43
..         ...
475       0.00
476       0.47
477       0.00
478       0.00
479       0.00

[480 rows x 7 columns]
     time_ly_14  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0      39.67       0.47       6.00       0.82      16.00
1           250      39.50       0.50       4.50       1.12      17.75
2           500      39.67       0.47       4.50       1.12      18.33
3           750      39.50       0.50       4.50       2.06      17.50
4          1000      39.33       0.47       5.33       0.47      17.00
..          ...        ...        ...        ...        ...        ...
475      118750      41.50       0.50      10.67       0.47      14.00
476      119000      41.50       0.50      10.80       0.40      14.40
477      119250      41.75       0.43      10.00       0.00      13.67
478      119500      42.00       0.00       9.40       0.49      14.00
479      119750      41.75       0.43       9.00       0.00      14.33

     var_rss23
0         1.00
1         0.43
2         0.47
3         0.50
4         0.71
..         ...
475       0.82
476       0.80
477       0.94
478       1.10
479       0.47

[480 rows x 7 columns]
     time_ly_15  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0      29.00       0.00       9.00       0.71       8.50
1           250      29.00       0.00       8.00       0.71       8.50
2           500      29.00       0.00       8.00       0.71       8.00
3           750      28.50       0.50       8.25       0.43       8.75
4          1000      29.00       0.00       8.75       1.09       9.00
..          ...        ...        ...        ...        ...        ...
475      118750      29.25       0.43       4.00       0.00      10.50
476      119000      29.25       0.43       4.00       0.00      10.25
477      119250      29.50       0.50       2.33       0.94       9.67
478      119500      29.00       0.00       2.67       0.47      10.00
479      119750      29.00       0.00       2.75       0.43      11.00

     var_rss23
0         0.50
1         0.50
2         1.00
3         0.43
4         0.00
..         ...
475       0.50
476       0.83
477       0.94
478       0.82
479       0.82

[480 rows x 7 columns]
     time_sit_1  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0      42.00       0.00      19.20       0.98      15.50
1           250      42.00       0.00      19.33       0.94      11.00
2           500      42.00       0.00      17.50       0.50      12.50
3           750      42.00       0.00      17.00       1.41      13.33
4          1000      42.00       0.00      17.50       0.87      12.00
..          ...        ...        ...        ...        ...        ...
475      118750      44.25       0.83      20.00       0.00      18.00
476      119000      44.25       0.43      20.00       0.00      17.75
477      119250      44.25       0.43      19.00       1.00      17.75
478      119500      44.75       0.43      17.00       0.71      15.00
479      119750      48.00       2.12      22.25       1.92      10.75

     var_rss23
0         2.06
1         0.82
2         0.50
3         0.94
4         0.82
..         ...
475       0.00
476       0.43
477       0.43
478       1.00
479       2.28

[480 rows x 7 columns]
     time_sit_2  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0      50.25       0.43      24.00       0.00       6.75
1           250      50.75       0.43      23.67       0.47       9.33
2           500      48.00       0.71      22.50       0.87       8.75
3           750      47.33       0.47      20.50       0.50      10.67
4          1000      47.50       0.50      21.00       0.00       8.50
..          ...        ...        ...        ...        ...        ...
475      118750      45.00       0.00      10.50       1.50      18.25
476      119000      45.00       0.00      12.00       0.00      18.25
477      119250      45.00       0.00       7.50       4.50      19.00
478      119500      45.00       0.00      12.75       1.48      19.40
479      119750      45.00       0.00      16.00       1.58      19.25

     var_rss23
0         1.92
1         0.94
2         1.09
3         0.94
4         0.50
..         ...
475       0.43
476       0.43
477       1.00
478       0.80
479       0.83

[480 rows x 7 columns]
     time_sit_3  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0       45.0        0.0      13.25       0.83      18.00
1           250       45.0        0.0      10.67       0.47      18.00
2           500       45.0        0.0      10.00       0.82      17.75
3           750       45.0        0.0      10.33       1.70      17.50
4          1000       45.0        0.0       4.33       1.70      12.50
..          ...        ...        ...        ...        ...        ...
475      118750       45.0        0.0       9.00       0.82      21.00
476      119000       45.0        0.0       6.67       0.94      21.00
477      119250       45.0        0.0       6.67       2.05      21.00
478      119500       45.0        0.0       5.50       1.50      21.00
479      119750       45.0        0.0       4.75       2.49      21.00

     var_rss23
0         0.00
1         0.00
2         0.43
3         0.50
4         1.50
..         ...
475       0.00
476       0.00
477       0.00
478       0.00
479       0.00

[480 rows x 7 columns]
     time_sit_4  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0       45.0        0.0       4.33       0.94      20.75
1           250       45.0        0.0       7.67       0.47      21.00
2           500       45.0        0.0       4.00       2.00      21.00
3           750       45.0        0.0       5.67       2.05      19.25
4          1000       45.0        0.0      11.50       0.50      18.25
..          ...        ...        ...        ...        ...        ...
475      118750       45.0        0.0       9.00       2.12      12.50
476      119000       45.0        0.0       7.67       1.70      13.75
477      119250       45.0        0.0       5.40       1.02      12.25
478      119500       45.0        0.0       7.50       2.29      13.25
479      119750       45.0        0.0       3.67       1.25      12.00

     var_rss23
0         0.43
1         0.00
2         0.00
3         1.30
4         0.43
..         ...
475       0.87
476       0.83
477       0.43
478       1.30
479       1.00

[480 rows x 7 columns]
     time_sit_5  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0      45.00       0.00       4.33       0.94      10.75
1           250      45.00       0.00       1.00       0.00      12.33
2           500      45.00       0.00       2.50       0.50      14.50
3           750      45.00       0.00       3.00       0.00      14.50
4          1000      45.00       0.00       3.00       0.82      15.25
..          ...        ...        ...        ...        ...        ...
475      118750      30.33       0.47      21.00       0.00      19.33
476      119000      30.00       0.00      21.25       0.43      20.25
477      119250      30.00       0.00      21.00       0.00      20.25
478      119500      30.00       0.00      21.00       0.00      20.50
479      119750      30.00       0.00      20.25       0.43      20.25

     var_rss23
0         2.17
1         1.25
2         1.12
3         1.12
4         0.43
..         ...
475       1.25
476       0.43
477       0.83
478       0.87
479       0.43

[480 rows x 7 columns]
     time_sit_6  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0      30.25       0.43      20.75       0.43      20.50
1           250      30.00       0.00      21.00       0.00      21.00
2           500      30.00       0.00      21.00       0.00      21.00
3           750      30.00       0.00      21.00       0.00      21.00
4          1000      30.00       0.00      21.25       0.43      21.00
..          ...        ...        ...        ...        ...        ...
475      118750      32.00       0.71       4.67       0.47      14.67
476      119000      31.25       0.43       3.50       0.50      13.25
477      119250      32.33       0.47       7.75       0.83      14.33
478      119500      33.00       0.00      11.50       0.50      14.00
479      119750      32.80       0.40      11.50       0.87      14.00

     var_rss23
0         0.50
1         0.00
2         0.00
3         0.00
4         0.00
..         ...
475       0.47
476       1.30
477       0.94
478       0.82
479       0.89

[480 rows x 7 columns]
     time_sit_7  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0             0      33.00       0.00      11.75       0.43      14.67
1           250      33.75       1.30      13.75       1.09      14.50
2           500      36.00       0.00      12.25       0.43      16.50
3           750      36.00       0.00      12.00       0.00      15.50
4          1000      36.00       0.00      11.75       0.43      15.75
..          ...        ...        ...        ...        ...        ...
475      118750      44.00       0.00      18.75       0.43       0.00
476      119000      44.25       0.43      18.75       0.43       3.00
477      119250      43.33       0.47      19.00       0.00       4.25
478      119500      44.00       0.00      18.75       0.43       4.50
479      119750      44.50       0.50      18.75       0.43       6.50

     var_rss23
0         0.47
1         1.12
2         0.87
3         0.50
4         0.83
..         ...
475       0.00
476       0.00

     time_stand_5  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0               0      45.00       0.00      18.25       0.43       9.50
1             250      45.00       0.00      20.00       0.00       9.00
2             500      44.75       0.43      18.75       0.43       9.75
3             750      44.33       0.47      18.25       0.43      11.00
4            1000      43.33       0.47      18.33       0.47      10.00
..            ...        ...        ...        ...        ...        ...
475        118750      47.25       0.43      11.75       3.96      18.25
476        119000      45.50       1.12      12.00       1.22      15.25
477        119250      40.75       1.92      14.00       1.41      19.67
478        119500      43.50       1.12      14.00       1.22       6.75
479        119750      45.50       0.50      10.50       1.12      13.75

     var_rss23
0         0.50
1         0.00
2         0.83
3         1.00
4         0.71
..         ...
475       3.70
476       4.26
477       1.25
478       3.77
479       4.76

[480 rows x 7 columns]
     time_stand_6  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0               0      44.50       0.87      11.25       5.54      12.50
1             250      42.50       0.87      18.00       0.71      14.25
2             500      39.00       2.12      16.00       1.58      13.75
3             750      36.25       0.43      18.67       0.47       9.50
4            1000      39.25       1.48      16.25       2.68       5.67
..            ...        ...        ...        ...        ...        ...
475        118750      45.00       0.00      21.00       0.00      13.00
476        119000      45.00       0.00      21.00       0.00      12.25
477        119250      45.00       0.00      21.00       0.00      12.50
478        119500      45.00       0.00      21.00       0.00      12.00
479        119750      45.00       0.00      20.80       0.40      12.75

     var_rss23
0         2.96
1         3.83
2         2.38
3         0.50
4         2.87
..         ...
475       0.82
476       0.43
477       0.87
478       0.00
479       0.83

[480 rows x 7 columns]
     time_stand_7  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0               0      45.00       0.00      19.00       0.82      10.00
1             250      45.33       0.47      15.67       0.94       9.75
2             500      45.25       0.43      16.00       0.71      11.50
3             750      45.25       0.43      17.75       1.09      10.00
4            1000      45.50       0.50      20.00       0.71      11.75
..            ...        ...        ...        ...        ...        ...
475        118750      48.00       0.00       9.00       0.71      12.00
476        119000      48.00       0.00       9.75       0.83      12.00
477        119250      48.00       0.00       7.00       2.12      10.60
478        119500      48.00       0.00       0.00       0.00       7.50
479        119750      48.00       0.00       0.00       0.00       8.33

     var_rss23
0         1.22
1         1.48
2         0.50
3         1.00
4         0.43
..         ...
475       0.00
476       0.00
477       1.36
478       1.50
479       2.87

[480 rows x 7 columns]
     time_stand_8  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0               0      48.00       0.00       6.75       3.77      11.00
1             250      47.75       0.43      11.50       0.50      10.00
2             500      48.00       0.00      11.25       0.43       8.67
3             750      48.00       0.00      11.67       0.47      11.00
4            1000      48.00       0.00      10.25       1.79      12.00
..            ...        ...        ...        ...        ...        ...
475        118750      46.00       0.82      18.00       0.00      13.25
476        119000      46.50       0.50      18.50       0.50      14.00
477        119250      46.50       0.50      18.75       0.83      14.00
478        119500      46.50       0.50      19.00       0.71      14.50
479        119750      46.25       0.43      18.50       0.50      15.00

     var_rss23
0         1.22
1         1.00
2         0.47
3         1.41
4         0.00
..         ...
475       1.09
476       0.71
477       1.00
478       0.50
479       0.71

[480 rows x 7 columns]
     time_stand_9  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0               0      46.25       0.43      18.25       0.43      14.75
1             250      46.00       0.71      18.50       0.87      14.25
2             500      46.25       0.83      18.50       0.87      13.75
3             750      46.25       0.83      18.67       0.47      14.00
4            1000      46.00       1.00      18.50       0.50      13.25
..            ...        ...        ...        ...        ...        ...
475        118750      44.50       0.50      18.75       0.83       5.25
476        119000      44.50       0.50      19.33       0.47       6.00
477        119250      44.50       0.50      19.25       0.83       7.25
478        119500      44.50       0.50      19.00       0.71       8.00
479        119750      44.67       0.47      18.00       0.00       9.00

     var_rss23
0         0.43
1         0.83
2         0.83
3         0.82
4         0.83
..         ...
475       1.79
476       0.82
477       1.30
478       0.71
479       0.00

[480 rows x 7 columns]
     time_stand_10  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0                0      44.50       0.50      15.00       0.71       9.25
1              250      44.75       0.43      13.00       0.71      11.25
2              500      41.33       0.94      15.33       0.47      11.00
3              750      39.50       0.87      16.75       1.09      10.00
4             1000      39.25       0.43      15.75       2.49      15.25
..             ...        ...        ...        ...        ...        ...
475         118750      45.00       0.00      17.75       0.43      13.00
476         119000      45.00       0.00      16.75       0.43      13.50
477         119250      45.00       0.00      16.00       0.00      12.75
478         119500      45.00       0.00      16.25       0.43      12.00
479         119750      45.00       0.00      17.00       0.00      12.00

     var_rss23
0         0.43
1         0.83
2         1.22
3         1.58
4         2.17
..         ...
475       1.00
476       0.87
477       0.43
478       0.00
479       0.00

[480 rows x 7 columns]
     time_stand_11  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0                0      45.00       0.00      17.25       0.43      13.50
1              250      45.00       0.00      17.75       0.43      13.75
2              500      45.00       0.00      17.25       0.43      13.75
3              750      45.00       0.00      16.50       1.12      14.67
4             1000      45.00       0.00      15.50       0.50      14.25
..             ...        ...        ...        ...        ...        ...
475         118750      38.75       0.43      17.25       0.43      17.75
476         119000      39.25       0.43      15.25       2.17      18.50
477         119250      41.75       0.43       7.33       3.40      16.25
478         119500      43.00       0.71      10.00       2.12      16.25
479         119750      44.00       0.00      14.00       0.00      15.00

     var_rss23
0         0.87
1         0.83
2         0.83
3         0.47
4         1.48
..         ...
475       0.43
476       0.87
477       1.30
478       0.83
479       0.71

[480 rows x 7 columns]
     time_stand_12  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0                0      43.75       0.83      14.75       0.43      14.25
1              250      45.00       0.00      17.67       0.47      12.50
2              500      45.25       0.43      17.25       0.83      11.75
3              750      45.00       0.00      16.00       1.00      12.33
4             1000      44.67       0.47      12.00       0.00      12.67
..             ...        ...        ...        ...        ...        ...
475         118750      44.67       0.47      12.25       0.43      15.00
476         119000      44.33       0.47      13.00       0.00      14.75
477         119250      45.00       0.00      12.00       0.00      15.00
478         119500      45.00       0.00      11.50       0.50      15.00
479         119750      45.00       0.00      12.00       0.00      15.00

     var_rss23
0         0.83
1         0.87
2         0.43
3         0.47
4         0.47
..         ...
475       0.00
476       0.43
477       0.71
478       0.00
479       0.00

[480 rows x 7 columns]
     time_stand_13  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0                0      45.00       0.00      12.50       0.87      14.50
1              250      45.00       0.00      13.00       0.00      14.00
2              500      45.00       0.00      12.00       0.00      13.50
3              750      45.00       0.00      13.33       0.47      12.50
4             1000      45.00       0.00      12.25       0.43      12.75
..             ...        ...        ...        ...        ...        ...
475         118750      40.50       0.50      12.75       1.30      17.00
476         119000      39.67       0.47      11.00       1.00      17.75
477         119250      40.25       0.83       8.25       0.83      18.00
478         119500      40.00       0.71       7.67       0.47      18.00
479         119750      39.75       0.83       8.00       0.71      18.00

     var_rss23
0         0.50
1         1.00
2         0.87
3         0.50
4         0.83
..         ...
475       0.71
476       0.83
477       0.00
478       0.00
479       0.00

[480 rows x 7 columns]
     time_stand_14  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0                0      39.50       0.50       9.00       0.00      18.00
1              250      39.25       0.43      11.00       1.00      17.50
2              500      39.25       0.43      12.00       0.00      16.50
3              750      39.00       0.00      11.00       0.71      16.75
4             1000      39.00       0.00      11.75       0.43      18.00
..             ...        ...        ...        ...        ...        ...
475         118750      45.00       0.00      15.50       0.87      13.00
476         119000      45.00       0.00      15.75       0.43      13.75
477         119250      44.50       0.87      17.25       0.83      15.75
478         119500      42.75       0.83      17.75       0.43      19.00
479         119750      42.00       0.00      20.67       0.47      17.00

     var_rss23
0         0.00
1         0.50
2         0.50
3         0.83
4         0.00
..         ...
475       1.00
476       1.09
477       1.48
478       1.00
479       0.82

[480 rows x 7 columns]
     time_stand_15  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0                0      41.50       0.87      19.75       1.30      10.25
1              250      40.33       0.47      14.00       1.63      12.25
2              500      40.25       0.83       7.00       0.00      10.50
3              750      40.50       0.50       9.00       0.00      12.67
4             1000      40.50       0.50      14.50       2.29      14.25
..             ...        ...        ...        ...        ...        ...
475         118750      45.25       0.43      12.25       0.43      13.75
476         119000      45.00       0.00      12.60       0.80      14.25
477         119250      45.00       0.00      12.00       0.00      14.50
478         119500      45.50       0.50      12.25       0.43      14.50
479         119750      45.00       0.00      12.50       0.87      14.00

     var_rss23
0         2.86
1         0.43
2         0.50
3         0.94
4         0.83
..         ...
475       0.83
476       0.83
477       0.50
478       0.50
479       0.71

[480 rows x 7 columns]
     time_wa_1  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      35.00       3.67      16.50       3.77      14.00
1          250      28.50       3.35      17.50       3.77      12.25
2          500      35.50       2.87      15.75       2.86      17.75
3          750      29.75      12.19      16.25       2.17      20.75
4         1000      27.00       2.12      16.75       0.83      24.75
..         ...        ...        ...        ...        ...        ...
475     118750      35.50       4.27      15.67       4.78      17.00
476     119000      30.75       2.49      18.50       4.15      18.00
477     119250      36.00       2.94      16.25       1.30      16.67
478     119500      37.40       6.15      10.25       5.31      14.60
479     119750      34.67       1.25      18.00       1.87       9.33

     var_rss23
0         1.63
1         3.90
2         5.07
3         2.59
4         1.64
..         ...
475       1.41
476       1.41
477       3.09
478       4.32
479       6.02

[480 rows x 7 columns]
     time_wa_2  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      24.50       4.77      16.50       4.50      13.75
1          250      40.00       5.24      19.25       2.86      12.25
2          500      40.00       2.83      17.00       1.41      16.75
3          750      37.75       0.83      16.00       5.15      16.25
4         1000      36.50       5.36      18.25       2.17      11.50
..         ...        ...        ...        ...        ...        ...
475     118750      27.75       5.76      13.25       1.30      16.25
476     119000      38.25       5.12      14.75       2.17      15.00
477     119250      34.00       2.83      17.00       5.39       9.00
478     119500      29.00       5.72      12.00       6.60      12.67
479     119750      38.67       5.79      13.00       1.41      15.75

     var_rss23
0         2.38
1         4.32
2         4.71
3         7.12
4         4.27
..         ...
475       2.49
476       6.36
477       4.97
478       5.44
479       3.34

[480 rows x 7 columns]
     time_wa_3  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      24.75       5.76      13.25       3.03      18.75
1          250      36.25       7.26      15.00       3.67      17.75
2          500      37.00       3.94      20.25       1.30      16.25
3          750      33.75       3.27      19.50       4.50      15.00
4         1000      34.25       5.21      17.00       1.22      14.25
..         ...        ...        ...        ...        ...        ...
475     118750      36.00       2.45      17.00       5.10      20.50
476     119000      34.33       1.89      15.00       2.45      17.00
477     119250      33.00       7.35      14.60       3.14      13.00
478     119500      31.67       1.25      11.00       6.16      19.25
479     119750      30.75      10.21      11.75       1.09      18.50

     var_rss23
0         1.48
1         2.86
2         1.64
3         2.12
4         4.15
..         ...
475       0.87
476       2.12
477       5.70
478       2.17
479       3.20

[480 rows x 7 columns]
     time_wa_4  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      38.50       3.77      15.50       1.80      20.50
1          250      33.67       3.86      13.33       3.40      16.00
2          500      40.33       6.55       9.67       3.30      18.00
3          750      34.50       5.59      15.33       4.50      22.75
4         1000      31.75       4.21      17.25       1.92      20.25
..         ...        ...        ...        ...        ...        ...
475     118750      34.75       7.66      14.50       2.18      12.00
476     119000      24.75       8.26      13.50       5.02      17.25
477     119250      26.25       2.49      18.75       3.56      12.50
478     119500      38.50       3.28      18.25       2.38      18.50
479     119750      35.50       1.50      14.00       2.12      20.75

     var_rss23
0         1.66
1         5.00
2         4.24
3         1.64
4         4.26
..         ...
475       5.79
476       4.32
477       7.09
478       2.06
479       3.27

[480 rows x 7 columns]
     time_wa_5  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      35.75       2.77      14.67       2.05      14.00
1          250      40.00       4.06      12.00       3.94      13.00
2          500      33.00       4.24      14.00       1.00      15.67
3          750      30.25       0.43      15.25       2.77      20.25
4         1000      40.00       0.82      13.25       5.80      21.00
..         ...        ...        ...        ...        ...        ...
475     118750      26.75       2.17      15.25       5.07      10.00
476     119000      30.75       2.49       9.25       2.05      17.00
477     119250      35.50       4.33      18.00       0.00      21.33
478     119500      27.25       2.17      17.50       3.84      15.75
479     119750      32.67       4.50      16.25       3.49      12.33

     var_rss23
0         0.00
1         7.38
2         2.62
3         7.40
4         2.94
..         ...
475       5.10
476       1.41
477       2.05
478       1.48
479       7.85

[480 rows x 7 columns]
     time_wa_6  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      39.00       6.48      12.67       0.94      17.67
1          250      31.75       2.49      16.25       5.31      17.00
2          500      34.00       2.83      16.33       3.40      16.33
3          750      38.50       6.06      18.00       2.12      14.25
4         1000      28.00       4.06      17.50       1.80      19.50
..         ...        ...        ...        ...        ...        ...
475     118750      44.00       1.41      19.67       2.05      14.25
476     119000      37.33       1.25      14.00       3.74      17.25
477     119250      27.75       7.29      13.67       6.18      20.75
478     119500      31.00       2.16      17.33       1.70      15.25
479     119750      33.00       6.40      18.50       2.87      12.67

     var_rss23
0         1.25
1         2.24
2         1.25
3         3.56
4         2.06
..         ...
475       1.79
476       3.90
477       0.43
478       4.02
479       2.49

[480 rows x 7 columns]
     time_wa_7  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      32.25       3.27      14.50       6.02      13.25
1          250      37.50       1.12      16.75       4.60      17.25
2          500      34.00       7.45      18.00       0.00      16.00
3          750      28.75       4.02      14.50       1.50      15.00
4         1000      37.50       5.41      15.25       4.44      14.67
..         ...        ...        ...        ...        ...        ...
475     118750      29.25       4.15      15.00       2.24      23.75
476     119000      42.67       2.87      16.00       2.92      19.33
477     119250      36.75       4.97      16.00       2.24      17.75
478     119500      43.67       2.36      19.00       2.83      14.75
479     119750      38.00       5.66      23.33       0.94      14.25

     var_rss23
0         4.02
1         4.32
2         2.55
3         2.55
4         1.25
..         ...
475       1.79
476       2.62
477       3.19
478       2.49
479       3.70

[480 rows x 7 columns]
     time_wa_8  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0            0      24.25      12.38      16.25       5.40      19.50
1          250      40.25       2.49      12.75       4.32      23.25
2          500      37.50       3.35      17.25       2.28      21.25
3          750      34.25       2.77      18.33       0.47      13.33
4         1000      40.50       3.20      13.00       1.73      20.25
..         ...        ...        ...        ...        ...        ...
475     118750      41.00       3.41      18.00       1.67      14.50
476     119000      27.00       3.08      20.00       0.71      20.50

      avg_rss12_mean avg_rss12_std avg_rss12_min avg_rss12_q1  \
b1_1         40.6248       1.47697         37.25        39.25
b1_2         42.8128       1.43555            38           42
b1_3         43.9545       1.55884            35           43
b1_4         42.1798       3.67067            33        39.15
b1_5         41.6781       2.24349            33        41.33
...              ...           ...           ...          ...
wa_11        33.5869       4.65094          19.5        30.25
wa_12        34.3227       4.75248         19.75           31
wa_13        34.5462       4.84229          19.5        31.25
wa_14        34.8732       4.53172          23.5        31.75
wa_15        34.4732       4.79671         19.25        31.25

      avg_rss12_median avg_rss12_q3 avg_rss12_max var_rss12_mean  \
b1_1              40.5           42            45       0.358604
b1_2              42.5        43.67         45.67       0.372438
b1_3             44.33           45          47.4        0.42625
b1_4              43.5           45         47.75       0.696042
b1_5             41.75        42.75         45.75       0.535979
...                ...          ...           ...            ...
wa_11            34.25           37         45.33        4.57656
wa_12            35.25           38          45.5        4.45633
wa_13            35.25      37.8125            46        4.37196
wa_14            35.25        38.25         46.25        4.38058
wa_15               35           38            44        4.35931

      var_rss12_std var_rss12_min  ... avg_rss23_median avg_rss23_q3  \
b1_1       0.322605             0  ...               35           36
b1_2       0.289158             0  ...               33         34.5
b1_3        0.33869             0  ...               36         36.5
b1_4        0.63086             0  ...               35        36.33
b1_5       0.405469             0  ...               30        31.25
...             ...           ...  ...              ...          ...
wa_11       2.46108             0  ...               16        18.25
wa_12       2.59928             0  ...            15.75        17.75
wa_13       2.36045             0  ...            15.75        17.75
wa_14       2.43544             0  ...               16           18
wa_15       2.38875             0  ...               16        17.75

      avg_rss23_max var_rss23_mean var_rss23_std var_rss23_min var_rss23_q1  \
b1_1          38.25       0.570583      0.582915             0            0
b1_2           38.5       0.571083       0.60101             0            0
b1_3           38.5       0.493292      0.513506             0            0
b1_4          38.67       0.613521      0.524317             0            0
b1_5           37.5       0.383292      0.389164             0            0
...             ...            ...           ...           ...          ...
wa_11            25        3.25973       1.64024             0         2.05
wa_12         23.25        3.43256       1.73273             0       2.1575
wa_13         22.75        3.33813       1.65674             0         2.16
wa_14          23.5        3.42465       1.69096             0         2.17
wa_15         23.25        3.34046       1.69911          0.43         2.12

      var_rss23_median var_rss23_q3 var_rss23_max
b1_1              0.43          1.3          1.92
b1_2              0.43          1.3          3.11
b1_3              0.43         0.94          1.79
b1_4               0.5            1          2.18
b1_5              0.43          0.5          1.79
...                ...          ...           ...
wa_11             3.11       4.3225          8.32
wa_12              3.2        4.565          9.67
wa_13             3.08        4.335            10
wa_14             3.27          4.5          9.51
wa_15             3.09        4.375             9

[88 rows x 42 columns]

'\n\nExtracted_Wholed_Features is a .csv file containing the required data, a summary\nof each instance\n\n\n'